name: fooling
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pytorch >= 1.13,< 2.0.2
  - torchvision
  - pytorch-cuda=11.8
  - lightning >= 2.0, <= 2.1
  - kornia
  - scikit-image
  - scikit-learn
  - matplotlib
  - pip:
    - torch-lucent
    - git+https://github.com/jeromerony/adversarial-library